feature: add environment configuration
IntershopCommunicationsAG/icm-docker-plugin pull request #65
Opened 2023-04-24 09:46 UTC by m-raab

2023-04-24 11:31 UTC, skiesewetter-intershop requested changes
The general concept of the ENVIRONMENT variable must be discussed.

2023-04-27 06:09 UTC, m-raab commented
> The general concept of the ENVIRONMENT variable must be discussed.

I think, as discussed: This variable is supported in ICM. But I think we need an other approach for the configuration, like configuration service.

2023-04-27 09:01 UTC, skiesewetter-intershop commented on src/main/kotlin/com/intershop/gradle/icm/docker/extension/DevelopmentConfiguration.kt
> +import java.util.*
A  *-import never is a good idea.

2023-04-27 09:06 UTC, skiesewetter-intershop requested changes

2023-04-27 09:06 UTC, skiesewetter-intershop commented on src/main/kotlin/com/intershop/gradle/icm/docker/extension/DevelopmentConfiguration.kt
> +                .replace(".", "_")
When providing properties using environment variables starting with `ISH_ENV_` it is not necessary to replace `.` by `_` and converting to upper case.

2023-04-27 09:46 UTC, skiesewetter-intershop approved these changes

2023-04-27 10:07 UTC, merged