fix: move user setting to mail server, add test
IntershopCommunicationsAG/icm-docker-plugin pull request #88
Opened 2023-11-30 08:34 UTC by m-raab

2023-11-30 10:57 UTC, skiesewetter-intershop requested changes

2023-11-30 11:21 UTC, cortlepp-intershop commented on src/main/kotlin/com/intershop/gradle/icm/docker/utils/mail/TaskPreparer.kt
> +            val os: OperatingSystem = DefaultNativePlatform.getCurrentOperatingSystem()
Maybe alternatively use `System.getProperty("os.name")`?

2023-11-30 12:07 UTC, m-raab commented on src/main/kotlin/com/intershop/gradle/icm/docker/utils/mail/TaskPreparer.kt
> +            val os: OperatingSystem = DefaultNativePlatform.getCurrentOperatingSystem()
Yes, you are correct - it is internal and a method with System.getProperty is possible. I asked StackOverflow for an approach that is working on different OSs. This internal API is not the only one and I think they will create also an external API.

2024-05-03 09:39 UTC, Thomas-Bergmann commented
is fixed at master (skiesewetter)

2024-05-03 09:39 UTC, closed without merging